# Generated by Django 3.1.3 on 2020-12-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
