# Generated by Django 3.1.3 on 2020-12-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201231_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
